### PR TITLE
Move Smack label loading to initramfs

### PR DESCRIPTION
**Pull request by ipuustin**
If one wants to reference Smack labels from IMA policy rules, the Smack labels need to be loaded before the IMA policy rules. Conditionally move Smack label loading to initramfs. The default behavior stays the same. This patch allows us to do rules such as "Don't calculate IMA hashes for root-owned data files", which can come handy.

The patch set is not thoroughly tested yet, but I'm posting this version to get feedback whether or not this is the right approach for solving the problem.

### CODE REVIEW

**Comment by ipuustin** [comment]
retest this please

**Comment by ipuustin** [comment]
retest this please

**Comment by ipuustin** [comment]
@pohly : should we consider closing or merging this?

**Comment by pohly** [comment]
Let's close this for now. It's an idea that's worth pursuing when we restart working on a better IMA/EVM setup, but for now it doesn't add much additional value and also (IMHO) would need further work. For example, it would be better to have a single, configurable file with the Smack rules that is then used both by initramfs and basefiles.

**Pull request closed without merging**
