### PR TITLE
integrate IMA/EVM

### PR DESCRIPTION
**Pull request by pohly**

### CODE REVIEW

**Comment by pohly** [comment]
I've updated the "integrity" branch with a fix for the systemd IMA loading bug and added the possibility to activate that feature in an image - see the updated (and reformatted) README.md.

**Comment by pohly** [comment]
@johnwhiteman: can you have a look at this PR? I'd prefer to have someone else verify it instead of self-merging it due to lack of reviewers.

**Comment by johnwhiteman** [comment]
@pohly.  I did perfunctory review with expectation that patches will be removed later in pull request.  Do you want me to merge pull request?

**Comment by pohly** [comment]
@johnwhiteman: did you also verify it by building and booting an image? Just wondering, it is not absolutely required for merging.

Yes, please merge. It serves as a permanent, public record in the git commit history that someone else looked at the PR.

**Comment by johnwhiteman** [comment]
@pohly For verification, I did not build and boot, but will merge anyway.  Sorry for the delay on this but work on the micro IoT side is taking many of my cycles.

**Pull request merged**
