### PR TITLE
smack: adding general testcases

### PR DESCRIPTION
**Pull request by acornea**
Tests checking general smack features, but no integration with
other components. Also covering smack over sockets and mmap.

### CODE REVIEW

**Comment by pohly** [comment]
There was no need to close PR #23. It would have been easier to force-push the commits replacing the previous commits on the same branch and that way get the PR updated.

**Comment by acornea** [comment]
I tried install_packages, without luck: binaries are not present on the target. I will update to use hasPackage, but I would suggest merging without install_packages at this point.

**Comment by acornea** [comment]
I amended my commit with the proposed changes.

**Comment by pohly** [comment]
One of the tests fails for me:

| ======================================================================
| ERROR: test_smack_mmap_enforced (oeqa.runtime.smack.SmackEnforceMmap)
| ----------------------------------------------------------------------
| Traceback (most recent call last):
|   File "/work/iot-os/meta/lib/oeqa/utils/decorators.py", line 86, in wrapped_f
|     return f(*args)
|   File "/work/meta-intel-iot-security/meta-security-smack/lib/oeqa/runtime/smack.py", line 449, in test_smack_mmap_enforced
|     self.target.run("chsmack -e %s %s" %(mmap_label, mmap_exe))
| NameError: global name 'mmap_exe' is not defined

**Comment by acornea** [comment]
Fixed. Issue introduced after switching how the test binaries are included in the image.

**Comment by pohly** [comment]
Now it fails with:

 ======================================================================
| FAIL: test_smack_mmap_enforced (oeqa.runtime.smack.SmackEnforceMmap)
| ----------------------------------------------------------------------
| Traceback (most recent call last):
|   File "/work/iot-os/meta/lib/oeqa/utils/decorators.py", line 86, in wrapped_f
|     return f(*args)
|   File "/work/meta-intel-iot-security/meta-security-smack/lib/oeqa/runtime/smack.py", line 461, in test_smack_mmap_enforced
|     "Should have mmap access without rules. Output: %s" %output)
| AssertionError: 127 != 0 : Should have mmap access without rules. Output: sh: mmap_test: command not found
| 
| ----------------------------------------------------------------------

I use this in my local.conf:

TEST_SUITES="smack"
CORE_IMAGE_EXTRA_INSTALL += "udp-smack-test tcp-smack-test mmap-smack-test"

**Comment by pohly** [comment]
There is an "mmap" command in the test package, but no mmap_test:

ls mmap-smack-test/1.0-r0/package/usr/bin/
mmap

**Comment by acornea** [comment]
Updated. Pushed the wrong changes initially.

**Comment by pohly** [comment]
Worked fine now, merging.

**Pull request merged**
