### PR TITLE
ima.py: increase delay in ima hash check test

### PR DESCRIPTION
**Pull request by acornea**
During testing, the hash seems to take longer to compute and
add in ascii_runtime_measurements. This increase should take care
of the false negative.

### CODE REVIEW

**Comment by pohly** [comment]
It also adds 30 seconds to the overall test time.

Please try to find a solution with quick polling on the target device and a timeout after 30 seconds.

**Comment by acornea** [comment]
Updated to try a maximum of 30 times, with 1s delay.

**Comment by pohly** [comment]
This is likely to run more than 30 seconds because it ignores the time to log in and run the test. It also has additional overhead. I think the best solution would be to run this loop on the device:
ssh ... 'start=$(date '+%s'); while [ $(expr $(date '+%s') - $start) -lt 10 ]; do if grep foo /dev/null; then exit 0; fi; sleep 1; done; exit 1'

**Comment by acornea** [comment]
From my point of view, the overhead should be low enough to ignore. 
Before this, we used a sleep(10), and sometimes it failed. This is why we needed to increase it in the first time. 
Using your suggestion (assuming -lt 20 or 30) will only reduce a very small amount of time (not tested, but I guess that less than 2-3seconds) from the proposed solution. 
Either way, I do not think a 30 second test is a long test - we have many more which take longer.

Furthermore, if the correct hash is calculated on time, it will exit early.

**Comment by pohly** [comment]
I still think the code could be improved to time out after exactly 30  seconds, but as you said, that shouldn't matter in practice, so let's merge it.

**Comment by pohly** [comment]
Tests failed with some likely unrelated problems, merging anyway.

**Pull request merged**
