### PR TITLE
Improving compatibility to yocto dizzy

### PR DESCRIPTION
**Pull request by jobol**
While trying to use meta-intel-iot-security for AGL developments, we faced issues because we had to use yocto in its version dizzy. This set of patches can be used in the master branch while allowing to still compile using yocto version dizzy.

### CODE REVIEW

**Comment by jobol** [comment]
Patrick, you are absolutely right and I made changes to the commit messages to improve it.

Then I pushed "in force" the changes.

**Comment by jobol** [comment]
I changed the patching of security-manager to make it just before configure

I don't find the reason why linux/xattr.h has also to be added

**Comment by jobol** [comment]
updated
works for dizzy
not tested with other poky distributions

**Comment by pohly** [comment]
Looks good so far, now I just need to figure out how to test all this against the different Yocto releases. It would be a shame to get it working now and then run into regressions again in the future.

**Comment by pohly** [comment]
I'm working on automated TravisCI testing against different OE-core versions. See the "travis" branch and https://bugzilla.yoctoproject.org/show_bug.cgi?id=8692

I'd like to get that running before merging this PR.

**Comment by jobol** [comment]
what's up here?

**Comment by pohly** [comment]
On Mon, 2015-11-16 at 00:15 -0800, jobol wrote:

> what's up here?

I'm still working on the TravisCI setup, see my previous comment.

**Comment by jobol** [comment]
oh sorry, i missed the previous comment. Thank you

**Comment by jobol** [comment]
what's up here?

**Comment by pohly** [comment]
Still working on the TravisCI integration. It's progressing slowly due to the many trial-and-error runs.

**Comment by pohly** [comment]
All commits merged into master as part of PR 73.

**Pull request closed without merging**
