### PR TITLE
cynara: bump to version 0.11

### PR DESCRIPTION
**Pull request by jobol**
Signed-off-by: José Bollo jose.bollo@iot.bzh

### CODE REVIEW

**Comment by pohly** [comment]
ok to test

**Comment by jobol** [comment]
It is hard for me to interprete the travis's failure
Do you have a hint?
I changed SYSTEMD_SYSTEM_UNITDIR to SYSTEMD_UNIT_DIR
and
set the SOCKET_DIR to /run/cynara (maybe was /tmp)
Does it explain?

**Comment by pohly** [comment]
Testing against OE-core master is currently broken - I suspect that Python3 is not recent enough or something is missing (OE-core moved to that).

The test against Jethro merely timed out. I could populate sstate to speed that up, but as it worked elsewhere I'm fine with just merging the PR.

**Comment by jobol** [comment]
It makes me think that there is already rust in the mechanic.
I submitted to cynara upstream patches for yocto and new systemd (https://github.com/Samsung/cynara/pull/16)
So I expect to drop the patch I put soon.
Check the antirust >-_-<

**Pull request merged**
