### PR TITLE
Smacknet python

### PR DESCRIPTION
**Pull request by Ajoyacr**
I have rebuild the smacknet services that it add some improvements of the service.

### CODE REVIEW

**Comment by Ajoyacr** [comment]
the class ip_monitor it comes from a project from David Wolinsky, I'd assume that the Copyright should continue. the project have a BSD-clause 3 license.

**Comment by pohly** [comment]
Please document the origin more explicitly in the code itself, by crediting David Wolinsky and linking to the file were this code was copied from.

Given this explanation, yes, we should stick to the original license.

The commit message only describes the change, but does not explain why taking the change is useful. Getting rid of a custom tool like netvalue is one advantage, but more important is that this update works without polling, right?

Only ipv4 is mentioned. What is the plan regarding ipv6?

**Comment by Ajoyacr** [comment]
you are right there's no need of been pooling the ip.   I still haven't got able to work with smack supporting ipv6 but it will extend this feature in a next patch. 
do you have any example about the documentation to another code?

**Comment by pohly** [comment]
On Thu, 2015-12-10 at 10:53 -0800, Alejandro Joya wrote:

> do you have any example about the documentation to another code?

You mean, how to document origin of the code? I would just add a comment
above the class that you copied, saying "Original author: .... Copied
from: ..."

**Comment by pohly** [comment]
@Ajoyacr please squash all commits. The second one currently just adds a copyright header, but with a commit message that describes something else entirely.

Also remove netvalue because it is no longer needed.

**Comment by Ajoyacr** [comment]
Done, changes  as suggested

**Comment by Ajoyacr** [comment]
@pohly do you suggest any other change?

**Comment by pohly** [comment]
@Ajoyacr no, it's fine now. I was just trying to get clean CI results also from TravisCI.

**Pull request merged**
