### PR TITLE
Remove Cynara and security-manager.

### PR DESCRIPTION
**Pull request by ipuustin**
In order to simplify the layer and focus on the components used in IoT and Ostro OS, remove Cynara and security-manager. This PR is also for discussion purposes -- should the recipes be maintained somewhere else?

### CODE REVIEW

**Comment by pohly** [comment]
@ipuustin can you add the comment describing the motivation for the change to the commit messages?

@jobol: you'll need to find a different place for Cynara and SecurityManager recipes.

**Comment by jobol** [comment]
ack (what else?...)

**Comment by pohly** [comment]
@ipuustin there's one "app-runas" left in .travis.yml. Please also remove that.

**Comment by ipuustin** [comment]
I updated the patches with the requested changes.

**Comment by pohly** [comment]
https://github.com/ostroproject/meta-ostro/pull/259 needs to be merged first. Expecting this as part of https://github.com/ostroproject/ostro-os/pull/177

**Comment by pohly** [comment]
retest this please

**Comment by pohly** [comment]
#177 merged -> retest this please

**Comment by pohly** [comment]
Unrelated compile error in Ostro, let's merge despite that.

**Pull request merged**
