### PR TITLE
smack tests: Improve testing

### PR DESCRIPTION
**Pull request by acornea**
Changed the test binaries copyTo path to /tmp/ from /usr/bin.
Adapted affected scripts to look for test binaries in PATH, and
if they are not found, check in /tmp/, or fail otherwise.
Modified test change self label for privileged and unprivileged 
processes

### CODE REVIEW

**Comment by pohly** [comment]
What is the motivation for this change? The "why" part is missing in the commit message.

Long term it would be better to introduce a distro variable for the location of additional binaries. For example, /tmp might be mounted noexec, rendering it useless for running binaries.

**Comment by acornea** [comment]
For IMA tests, we plan to check all binaries in /bin and /usr/bin. Pushing test binaries there is not desirable, as they will not have signature in place, potentially failing the test. I agree that a distro path variable for pushing binaries would be good, but needs to be discussed with whole QA.

**Comment by pohly** [comment]
Please add this explanation to the commit message.

**Comment by acornea** [comment]
Updated commit message.

**Pull request merged**
