### PR TITLE
layer dependencies: make meta-security-framework the foundation

### PR DESCRIPTION
**Pull request by pohly**
The main motivation is that both Smack and IMA need the enhanced
e2fsprogs, so now they are in meta-security-framework. The keyutils
recipe also gets moved there, because it may also be useful without
using meta-integrity. The xattr-images.bbclass which is needed for
preserving xattrs in IMA-enabled images already was in
meta-security-framework before.

This dependency was different before because some recipes in
meta-security-framework depend on Smack. Even if not used, having them
in an enabled layer would have broken world builds. Now that gets
handled properly by disabling these recipes when the smack distro
feature is disabled.

This might also solve a build issue when switching the smack feature
on and off in the same build directory: that leads to file conflicts
between dbus-cynara and dbus, which might get avoided now (untested)
because OE-core removes files from recipes that it can no longer build
(like dbus-cynara when Smack gets disabled).

Signed-off-by: Patrick Ohly patrick.ohly@intel.com

### CODE REVIEW

**Comment by pohly** [comment]
@jobol @ipuustin please help review.

**Comment by jobol** [comment]
This is a major evolution. I agree with it for many reasons.

**Comment by elvinongbl** [comment]
Patrick,
Boon Leong here. I have reviewed the change and they look really good. I will be testing them soon.

**Comment by pohly** [comment]
@elvinongbl do you want me to merge so that you can test, or do you want to test first?

**Comment by pohly** [comment]
Let's merge and fix any undetected problems later, should any arise.

**Pull request merged**
