### PR TITLE
systemd: support v225

### PR DESCRIPTION
**Pull request by pohly**
Updated and cleaned up patches, suitable for v225. V219 is
still supported, for those who have not updated OE-core master
yet.

### CODE REVIEW

**Comment by pohly** [comment]
@cschaufler: can you review the update systemd patch (0005-tizen-smack-Handling-network-v225.patch)? Do you know whether that and 0003-tizen-smack-Handling-of-run-and-sys-fs-cgroup.patch were ever submitted upstream, or of any reason why they should not be sent upstream?

**Comment by mythi** [comment]
Looks good, +1

**Comment by pohly** [comment]
@cschaufler: I've merged the patches, but we should still discuss their upstream status.

**Comment by cschaufler** [comment]
I don't see any problems. +1
I don't know if these have been sent upstream.

**Pull request merged**
