### PR TITLE
Buxton recipe

### PR DESCRIPTION
**Pull request by topikuu**
Buxton is a Smack-compatible key-value management system. This is a baseline recipe for it.

### CODE REVIEW

**Comment by topikuu** [comment]
I fixed the issues you mentioned. At least systemd recipe has LICENSE = "GPLv2 & LGPLv2.1 & MIT" so I used equivalent format.

**Comment by pohly** [comment]
Looks good now. However, please squash the commits into one.

**Comment by pohly** [comment]
Samsung announced Tizen 3.0 Milestone 1 and mentions a Buxton2 in it, with support for Cynara. I suspect that this is a better match for a security architecture based on the Smack 3 domain model + Cynara.

**Comment by johnwhiteman** [comment]
Are you suggesting we wait until Buxton2 is evaluated before doing anything with this request?

**Comment by jobol** [comment]
Using Buxton with only smack isn't working well for Tizen 3. Buxton is much more useful with cynara.

**Comment by pohly** [comment]
@johnwhiteman yes, I think we need a better understanding of how Buxton would fit into the security model before merging the PR. What @Jobol said confirms my suspicion that it simply wouldn't be suitable.

Buxton2 might be, but there's very little information about it available. The source is here: https://review.tizen.org/git/?p=platform/core/system/buxton2.git;a=log;h=refs/heads/tizen - but it starts with a major code dump and doesn't have any README explaining the concepts behind it.

**Comment by otcuser** [comment]
Can one of the admins verify this patch?

**Comment by pohly** [comment]
I'm closing this as a specific need for Buxton has not materialized.

**Pull request closed without merging**
