### PR TITLE
Smacknet label configuration

### PR DESCRIPTION
**Pull request by Ajoyacr**
Related-to: IOTOS-771 IOTOS-807 IOTOS-808.
Provide network configuration to netlabel  for Smack.

Signed-off-by: Alejandro Joya alejandro.joya.cruz@intel.com

### CODE REVIEW

**Comment by ipuustin** [comment]
Please add header boilerplate (license terms and copyright statements) to the C file and script.

**Comment by ipuustin** [comment]
Would you consider converting smacknet also to a separate stand-alone recipe, like netvalue is done now? The meta-security-framework layer might be the right place for it.

**Comment by Ajoyacr** [comment]
I have built the smacknet service as stand alone and  added the license appropriate license headers

**Comment by ipuustin** [comment]
This starts to look good. However, you don't need to patch your own patches, like adding and then removing smacknet from smack recipe. Just create a suitable patch set and force push it to the same branch from which you made your PR.

**Pull request merged**
