### PR TITLE
TravisCI integration

### PR DESCRIPTION
**Pull request by pohly**
This contains the rebased patches from PR #66 plus additional fixes needed to get compilation working with Dizzy, Jethro, Fido and master. Compilation against master recently broke when dbus.inc was removed, against Jethro/Fido when a patch specific to the dbus version was added to it.

More importantly, this branch adds automatic testing against these branches under TravisCI. See the extended top-level README.md for details.

### CODE REVIEW

**Comment by pohly** [comment]
It is normal that the current test builds haven't succeeded yet. They need to be restarted a few times because compilation takes too long after a recent OE-core master update; I'm still in the process of doing that.

**Comment by pohly** [comment]
TravisCI testing passed, internal CI also looking good (but still running).

@mythi this PR has the dbus-cynara build fix for OE-core master.

@jobol note that this now has your commits as well as some additional fixes needed for Dizzy.

@acornea please check the test fixes.

**Comment by pohly** [comment]
@rossburton @rpurdie: the rm_work enhancements are good enough for now, but I plan to enhance them as time permits. I'm not happy about having to hard-code the list of tasks. See https://github.com/01org/meta-intel-iot-security/blob/travis2/README.md for a description.

**Comment by jobol** [comment]
@pohly: I had delay in check because commit 7e3db928a2c06cac7746e11bb06fee70979e9ec2 introduced new references to tzplatform... that I remove.
So now it build and seems to run. Okay for me. Thanks

**Comment by mythi** [comment]
@pohly +1. OK to merge.

**Pull request merged**
