### PR TITLE
tizen-platform-wrapper: fix resource leak

### PR DESCRIPTION
**Pull request by izaman**
'sum' is free'd when it is not in use anymore

Signed-off-by: Imran Zaman imran.zaman@intel.com

### CODE REVIEW

**Comment by izaman** [comment]
upstream patch: https://review.tizen.org/gerrit/47754

**Comment by jobol** [comment]
As the guilty author, I'd like to say that in principle tools aren't daemon and this tool is run one time in construction and it exits on error thus .... the problem is smaller than an electro.

Also why to release any memory when you exit? Why closing files? It isn't need in most cases. Only cases with side effect might need some clean up but frankly it is a lake of design. In theory any interdependent process should be aware that other processes can be defective.

**Comment by jobol** [comment]
in fact there is an organized leak in tizen-config but it is elsewhere and it is a shame. At first I implemented a scratch only buffer but most programmers dont understand the use of a global buffer so that unleaked implementation was removed. Nota bene that the scratch could have been set by thread using thread variables.

**Comment by izaman** [comment]
@pohly done.. thanks for reminder

**Comment by pohly** [comment]
@izaman: my comment was about the 0001-fix-resource-leak.patch file, not about the commit message for IoT OS. What's pending is that patch, not the meta-intel-iot-security change. Can you move it there?

@jobol: can you help getting  https://review.tizen.org/gerrit/47754 and https://review.tizen.org/gerrit/47663 reviewed or do we depend on Tizen maintainers for that?

**Comment by izaman** [comment]
@pohly done

**Pull request merged**
