### PR TITLE
smack fixes

### PR DESCRIPTION
**Pull request by pohly**
Local networking under runqemu no longer worked because
/var/lib/connman/wired.config had wrong Smack labels.
The solution for that may also be useful for labeling all
files with security.SMACK64=_ explicitly, to overcome the
"swupd does not work with Smack enabled" problem.

The change triggers a mkfs.ext4 bug when multiple xattrs
are present, so this also gets fixed. Because the layer is
also used with older OE-core releases, e2fsprogs had to be
copied. It only gets used for older OE-core releases.

Disabling the "smack" distro feature did not really disable Smack in
the kernel.

### CODE REVIEW

**Comment by pohly** [comment]
@ipuustin can you review this?

**Comment by ipuustin** [comment]
I think this patch set looks good. I just had very minor gripes. +1

**Comment by pohly** [comment]
Force-pushed the revised commit with "install -d"

**Comment by pohly** [comment]
Re-tested again against latest OE-core master, which has the same e2fsprogs fix as this PR => no problem, merging.

**Pull request merged**
