### PR TITLE
IMA: policy which supports hashing, initramfs support

### PR DESCRIPTION
**Pull request by pohly**
Right now, these features don't do anything unless a distro explicitly
enables them by setting up a suitable initramfs.

### CODE REVIEW

**Comment by johnwhiteman** [comment]
Security team is reviewing now. Please wait before merging.

**Comment by johnwhiteman** [comment]
Is it possible to setup a meeting next week to hash over (no pun intended) IMA policy? An ima expert external to team will have time to review and Casey will be back in case he has concerns  I will set the meeting up.

**Comment by pohly** [comment]
Yes, we can have a meeting to discuss this further.

**Comment by johnwhiteman** [comment]
This can be merged without said meeting. Please see comments though.

**Comment by mythi** [comment]
@pohly @johnwhiteman Looks like this PR includes systemd v225 fixes too and therefore overlaps with PR #45 and therefore the v225 is twice(?) in the history.

**Comment by pohly** [comment]
@johnwhiteman please check our CI status before merging. We can discuss internally how to do that. This PR could be merged cleanly by Github, but because of the issue that @mythi  mentioned, our CI and combo-layer choke on it.

I've fixed this by rewriting history on our master branch.

**Comment by johnwhiteman** [comment]
@pohly @mythi . Ahh, my apologies. Thank you for fixing.

**Pull request merged**
