### PR TITLE
Cynara + D-Bus + security-manager-policy

### PR DESCRIPTION
**Pull request by pohly**
This updates SecurityManager to 1.0.2 from Github, enables loading of the default policy (via the new security-manager-policy package's postinst), and optionally patches D-Bus to use Cynara.

### CODE REVIEW

**Comment by pohly** [comment]
The D-Bus patches are work in progress. Reviewing them in-depth here is not needed and should better be done in cooperation with the Samsung maintainers in Tizen.

**Comment by pohly** [comment]
@johnwhiteman: will you have time to review this soonish, say in the next few days?

**Comment by johnwhiteman** [comment]
Reviewed and built.  I do have a question regarding logistic. As we apply changes to make work in IoT, but want feedback from Samsung folks, is this code shareable?

**Comment by pohly** [comment]
@johnwhiteman: yes, absolutely. The entire repo is public intentionally, so that we can point others towards it and get feedback. Search for meta-intel-iot-security and you will see that it was announced already in a few places and is included in the OpenEmbedded metadata index.

**Comment by johnwhiteman** [comment]
Great!  This makes things easy.

**Pull request merged**
